// GhosttyConfigBridge.swift
// Limpid — translates the high-level `LimpidSettings` Codable into
// the `key = value\n` text format libghostty parses, and applies it
// to the running app. Two responsibilities:
//
//   1. **Serialize**: emit a config string the user could in
//      principle hand-write. Used at boot (written to a temp file
//      and loaded via `ghostty_config_load_file`) and at every live
//      reload.
//
//   2. **Force forbidden keys**: regardless of what `LimpidSettings`
//      or the user's `~/.config/ghostty/config` contain, certain
//      keys are pinned to values Limpid's chrome assumes (transparent
//      pane, no native window decoration, etc.). The forced lines
//      go *last* in the file so libghostty's last-write-wins
//      semantics override anything else.
//
// We deliberately don't pre-parse user config to filter forbidden
// keys; the cheaper trick of "append our values at the end" gets the
// same effect because libghostty merges in file order.

import Foundation
import GhosttyKit
import OSLog

private let log = Logger(subsystem: "dev.limpid", category: "ghostty.config-bridge")

@MainActor
enum GhosttyConfigBridge {

    // MARK: - Serialization

    /// Build the full `key = value\n` string Limpid wants libghostty
    /// to evaluate. Order matters: user-facing settings first so the
    /// forced-overrides section at the bottom always wins.
    static func makeConfigString(
        settings: LimpidSettings,
        resourcesDir: String?
    ) -> String {
        var lines: [String] = [
            "# Generated by Limpid. Edits here are overwritten on every settings change.",
            "# Settings UI: ⌘, — file: \(SettingsStore.settingsFileURL.path)",
            ""
        ]

        // MARK: User-facing settings → libghostty keys

        //
        // We don't wire Theme here — we use our own `WindowTint`
        // painted onto the L2/L3 column fills
        // instead of libghostty's `theme` key. ANSI palette + cell
        // text colours stay at libghostty's defaults.

        // Font
        if let family = settings.font.family, !family.isEmpty {
            lines.append("font-family = \(family)")
        }
        lines.append("font-size = \(settings.font.size)")
        if settings.font.ligatures {
            // Empty value clears libghostty's default "calt = 0" so
            // ligatures activate. Non-empty enables specific
            // OpenType features — left as default for now.
            lines.append("font-feature = ")
        } else {
            lines.append("font-feature = -calt")
        }
        if settings.font.lineHeight != 0 {
            lines.append("adjust-cell-height = \(Int(settings.font.lineHeight))")
        }

        // Terminal
        lines.append("scrollback-limit = \(settings.terminal.scrollbackLines)")
        lines.append("cursor-style = \(mapCursorStyle(settings.terminal.cursorStyle))")
        lines.append("cursor-style-blink = \(settings.terminal.cursorBlink)")
        lines.append("bell-features = \(mapBellFeatures(settings.terminal.bellAction))")

        // MARK: Resources dir (so shell-integration scripts resolve)

        if let resourcesDir {
            lines.append("resources-dir = \(resourcesDir)")
        }

        // MARK: Forced overrides — must go LAST so libghostty's

        // last-write-wins merging guarantees they stick even if user
        // config or some earlier line set them otherwise.

        lines.append("")
        lines.append("# Limpid forced overrides — do not override these in user config.")
        lines.append("# Liquid Glass chrome relies on these exact values.")
        // Terminal cells stay fully transparent — the wallpaper /
        // window opacity is the user-facing transparency knob, not
        // libghostty's per-cell tint. The trade-off is that Theme
        // only colours text + ANSI palette (not the cell bg), which
        // is the design we chose to keep Limpid's chrome consistent
        // across themes.
        lines.append("background-opacity = 0")
        // Fall back to xterm-256color so we don't depend on a
        // user-installed `xterm-ghostty` terminfo entry.
        lines.append("term = xterm-256color")
        // Limpid handles its own close-confirm via SwiftUI .alert,
        // so disable libghostty's confirm dialog.
        lines.append("confirm-close-surface = false")
        // Tell shell-integration to keep its hands off the cursor.
        // Default zsh / fish integration sends DECSCUSR (`ESC[<n> q`)
        // on every prompt, which clobbers Limpid's `cursor-style`
        // preference on the next keystroke. We own this setting
        // through Settings → Terminal → Cursor, so the prompt-time
        // override is always wrong here. (See Ghostty discussions
        // #3836 / #5144 / #8681 — the long-standing pitfall behind
        // "cursor-style doesn't change on existing shells".)
        lines.append("shell-integration-features = no-cursor")

        return lines.joined(separator: "\n") + "\n"
    }

    /// Write the config string to a stable temp file and return its
    /// path. Caller passes the path to `ghostty_config_load_file`.
    /// The same path is reused for live reloads — `update_config`
    /// looks at file mtime, so we overwrite atomically.
    static func writeConfigFile(settings: LimpidSettings, resourcesDir: String?) -> String? {
        let body = makeConfigString(settings: settings, resourcesDir: resourcesDir)
        let dir = (NSTemporaryDirectory() as NSString).appendingPathComponent("dev.limpid")
        try? FileManager.default.createDirectory(atPath: dir, withIntermediateDirectories: true)
        let path = (dir as NSString).appendingPathComponent("ghostty-config.limpid")
        do {
            try body.write(toFile: path, atomically: true, encoding: .utf8)
            return path
        } catch {
            log.error("config file write failed: \(String(describing: error), privacy: .public)")
            return nil
        }
    }

    // MARK: - Live reload

    /// Rebuild the libghostty config from the current `LimpidSettings`
    /// and push it into the running app. Triggers
    /// `Notification.Name.limpidConfigDidChange` so SwiftUI views
    /// (and per-surface code) can react in the same tick.
    ///
    /// Surfaces opened *before* this call retain settings that
    /// libghostty marks as "new-terminal only" (font family, ligatures,
    /// scrollback — see `Reloadability.newTerminal`). Settings the
    /// Schema marks as `.live` (font size, theme, opacity, cursor)
    /// apply to every running surface immediately.
    static func reloadConfig(
        app: GhosttyApp,
        settings: LimpidSettings,
        resourcesDir: String?,
        includeUserConfig: Bool
    ) {
        let path = writeConfigFile(settings: settings, resourcesDir: resourcesDir)
        guard let cfg = makeConfig(path: path, includeUserConfig: includeUserConfig) else {
            log.error("ghostty_config_new() returned nil during reload")
            return
        }
        // `App.zig::updateConfig` walks the surface list internally
        // and pushes a `change_config` message to every one, so a
        // single app-level call is enough — no per-surface loop
        // needed. (Ghostty's macOS app does the same.) `cfg`
        // ownership transfers in; do not free here.
        ghostty_app_update_config(app.handle, cfg)
        NotificationCenter.default.post(
            name: .limpidConfigDidChange,
            object: nil
        )
        log.notice("ghostty config reloaded")
    }

    /// Build a finalized libghostty config from the on-disk Limpid
    /// config file. The caller owns the returned handle — pass it to
    /// exactly one `ghostty_*_update_config` call.
    private static func makeConfig(path: String?, includeUserConfig: Bool) -> ghostty_config_t? {
        guard let cfg = ghostty_config_new() else { return nil }
        // Optional Layer 2: user's ~/.config/ghostty/config.
        // Forbidden keys still get neutralized because our forced
        // overrides append below them.
        if includeUserConfig {
            ghostty_config_load_default_files(cfg)
        }
        // Layer 3 + 4: Limpid settings + forced overrides.
        if let path {
            path.withCString { ghostty_config_load_file(cfg, $0) }
        }
        ghostty_config_finalize(cfg)
        return cfg
    }

    // MARK: - Mapping helpers

    /// Limpid's `CursorStyle` → libghostty's `cursor-style` value.
    private static func mapCursorStyle(_ style: CursorStyle) -> String {
        switch style {
        case .block: "block"
        case .bar: "bar"
        case .underline: "underline"
        }
    }

    /// Limpid's `BellAction` → libghostty's `bell-features` flags.
    /// Multiple flags space-separated.
    private static func mapBellFeatures(_ action: BellAction) -> String {
        switch action {
        case .none: "no-visual,no-audio,no-system,no-attention,no-title"
        case .visual: "visual,attention,no-audio,no-system"
        case .audio: "audio,attention,no-visual,no-system"
        case .both: "visual,audio,attention,no-system"
        }
    }
}

// MARK: - Notification name

extension Notification.Name {
    /// Posted by `GhosttyConfigBridge.reloadConfig` after libghostty
    /// has accepted the new config. Listeners (SwiftUI views, the
    /// SurfaceRegistry) re-evaluate any local cache that mirrored
    /// the old settings.
    static let limpidConfigDidChange = Notification.Name("dev.limpid.configDidChange")
}
