// GhosttyConfigBridge.swift
// Limpid — translates `LimpidSettings` into the `key = value\n` text
// libghostty parses, and applies it to the running app. The forced
// keys (transparent pane, no native window decoration, …) go *last*
// in the file so libghostty's last-write-wins merge silently
// overrides anything the user, `~/.config/ghostty/config`, or our
// own earlier lines wrote — cheaper than pre-parsing to filter.

import Foundation
import GhosttyKit
import OSLog

private let log = Logger.limpid("ghostty.config-bridge")

@MainActor
enum GhosttyConfigBridge {

    // MARK: - Serialization

    /// Light vs dark — passed in by the caller so we can pin a single
    /// theme to the current macOS appearance. libghostty's own
    /// `theme = light:X,dark:Y` syntax doesn't follow appearance
    /// changes when embedded (ghostty#11017), so we pick one side at
    /// config-write time and re-write on appearance change. The
    /// live-switch path runs through `reloadConfig`.
    enum Appearance { case light, dark }

    /// Build the full `key = value\n` string Limpid wants libghostty
    /// to evaluate. Order matters: user-facing settings first so the
    /// forced-overrides section at the bottom always wins.
    static func makeConfigString(
        settings: LimpidSettings,
        resourcesDir: String?,
        appearance: Appearance
    ) -> String {
        var lines: [String] = [
            "# Generated by Limpid. Edits here are overwritten on every settings change.",
            "# Settings UI: ⌘, — file: \(SettingsStore.defaultSettingsFileURL.path)",
            ""
        ]

        // MARK: - User-facing settings → libghostty keys

        // Font
        if let family = settings.font.family, !family.isEmpty {
            // Strip any line terminator the value happens to carry —
            // libghostty's config is line-oriented, so an embedded
            // newline in a hand-edited `settings.json` would otherwise
            // inject extra config keys (`window-decoration = client`,
            // `command = …`) BEFORE the forced-overrides block. The
            // picker only offers `NSFontManager` families today, but
            // defensive sanitization at the splice site is cheap.
            let sanitized = family.replacingOccurrences(of: "\n", with: " ")
                .replacingOccurrences(of: "\r", with: " ")
            lines.append("font-family = \(sanitized)")
        }
        lines.append("font-size = \(settings.font.size)")
        if settings.font.ligatures {
            // Empty value clears libghostty's default "calt = 0" so
            // ligatures activate. Non-empty enables specific
            // OpenType features — left as default for now.
            lines.append("font-feature = ")
        } else {
            lines.append("font-feature = -calt")
        }
        if settings.font.lineHeight != 0 {
            lines.append("adjust-cell-height = \(Int(settings.font.lineHeight))")
        }

        // Terminal
        lines.append("scrollback-limit = \(settings.terminal.scrollbackLines)")
        lines.append("cursor-style = \(mapCursorStyle(settings.terminal.cursorStyle))")
        lines.append("cursor-style-blink = \(settings.terminal.cursorBlink.isOn)")
        lines.append("bell-features = \(mapBellFeatures(settings.terminal.bellAction))")

        // MARK: - Resources dir (theme lookup only)

        // The `resources-dir` config key only affects libghostty's
        // bundled-theme resolution (see the absolute theme path below).
        // It does NOT feed shell integration — that path comes from
        // `$GHOSTTY_RESOURCES_DIR`, which we export before `ghostty_init`
        // in `GhosttyApp.bootstrap`. Keep both in sync if the layout moves.
        if let resourcesDir {
            lines.append("resources-dir = \(resourcesDir)")
        }

        // Theme: pick the bundled `Apple System Colors` pair so the
        // cell foreground + ANSI palette track macOS Terminal.app.
        // Must come AFTER `resources-dir` and uses an
        // absolute path because libghostty's named-theme lookup only
        // checks `~/.config/ghostty/themes/` and a hardcoded
        // `Ghostty.app/...` — neither sees our Limpid.app bundle.
        if let resourcesDir {
            let themePath = switch appearance {
            case .light: "\(resourcesDir)/themes/Apple System Colors Light"
            case .dark: "\(resourcesDir)/themes/Apple System Colors"
            }
            lines.append("theme = \(themePath)")
        }

        // MARK: - Forced overrides — must go LAST so libghostty's

        // last-write-wins merging guarantees they stick even if user
        // config or some earlier line set them otherwise.

        lines.append("")
        lines.append("# Limpid forced overrides — do not override these in user config.")
        lines.append("# Liquid Glass toolbar relies on these exact values.")
        // Terminal cells stay fully transparent — the wallpaper /
        // window opacity is the user-facing transparency knob, not
        // libghostty's per-cell tint. The trade-off is that Theme
        // only colors text + ANSI palette (not the cell bg), which
        // is the design we chose to keep Limpid's toolbar consistent
        // across themes.
        lines.append("background-opacity = 0")
        // Fall back to xterm-256color so we don't depend on a
        // user-installed `xterm-ghostty` terminfo entry.
        lines.append("term = xterm-256color")
        // Limpid handles its own close-confirm via SwiftUI .alert,
        // so disable libghostty's confirm dialog.
        lines.append("confirm-close-surface = false")
        // Tell shell-integration to keep its hands off the cursor.
        // Default zsh / fish integration sends DECSCUSR (`ESC[<n> q`)
        // on every prompt, which clobbers Limpid's `cursor-style`
        // preference on the next keystroke. We own this setting
        // through Settings → Terminal → Cursor, so the prompt-time
        // override is always wrong here. (See Ghostty discussions
        // #3836 / #5144 / #8681 — the long-standing pitfall behind
        // "cursor-style doesn't change on existing shells".)
        lines.append("shell-integration-features = no-cursor")
        // Limpid never loads custom shaders, so disable the draw timer
        // that fires at 120 Hz (DRAW_INTERVAL = 8 ms) when the surface
        // is focused. Without this, every focused surface burns ~120
        // wakeups/s even at idle.
        lines.append("custom-shader-animation = false")

        // MARK: - Pattern A — single source of truth for keybinds

        //
        // Wipe libghostty's built-in macOS defaults so the menu bar
        // owns every shortcut; without `clear` a user remap (e.g.
        // "New Tab" → ⌘⇧T) would leave libghostty still firing its
        // own ⌘T behind the user's back. Forced bindings + the
        // user-configured action keybinds get re-emitted below.
        lines.append("keybind = clear")
        // Defense-in-depth against libghostty's `super+q=quit`
        // racing AppKit's terminate path (which fires
        // `applicationWillTerminate` and persists scrollback). ⌘Q is
        // already routed to the menu via
        // `SurfaceView.performKeyEquivalent`, but unbinding here
        // covers any future keystroke-routing change.
        lines.append("keybind = super+q=unbind")
        // Legacy XTerm key encoding emits identical bytes for ↩
        // and ⇧↩, so TUIs can't tell them apart. Mapping ⇧↩ to a
        // literal newline matches the recommended bare-ghostty
        // workaround (ghostty discussion #7780).
        lines.append(#"keybind = shift+enter=text:\n"#)

        lines.append(contentsOf: actionKeybindLines(settings: settings))

        return lines.joined(separator: "\n") + "\n"
    }

    /// One `keybind = …` line per `LimpidShortcutAction` with a
    /// configured trigger. Ghostty-dispatched actions
    /// (`ghosttyAction != nil`) emit the real action so libghostty
    /// fires it when the terminal has focus. Menu-owned actions
    /// (`ghosttyAction == nil`) emit `=ignore` — a disabled menu
    /// item lets the keystroke fall through to the focused
    /// terminal, and without `ignore` libghostty would type the
    /// literal character ("j", "R", …). An enabled menu item
    /// consumes the event before libghostty sees it, so `ignore`
    /// only fires on the disabled path.
    private static func actionKeybindLines(settings: LimpidSettings) -> [String] {
        var out: [String] = []
        for action in LimpidShortcutAction.allCases {
            guard let shortcut = settings.keyboard.shortcut(for: action) else { continue }
            let rhs = action.ghosttyAction ?? "ignore"
            out.append("keybind = \(shortcut.ghosttyTrigger)=\(rhs)")
        }
        return out
    }

    /// Write the config string to a stable temp file and return its
    /// path. Caller passes the path to `ghostty_config_load_file`.
    /// The same path is reused for live reloads — `update_config`
    /// looks at file mtime, so we overwrite atomically.
    static func writeConfigFile(
        settings: LimpidSettings,
        resourcesDir: String?,
        appearance: Appearance
    ) -> String? {
        let body = makeConfigString(
            settings: settings,
            resourcesDir: resourcesDir,
            appearance: appearance
        )
        let dir = (NSTemporaryDirectory() as NSString).appendingPathComponent("dev.limpid")
        try? FileManager.default.createDirectory(atPath: dir, withIntermediateDirectories: true)
        let path = (dir as NSString).appendingPathComponent("ghostty-config.limpid")
        do {
            try body.write(toFile: path, atomically: true, encoding: .utf8)
            return path
        } catch {
            log.error("config file write failed: \(String(describing: error), privacy: .public)")
            return nil
        }
    }

    // MARK: - Live reload

    /// Rebuild the libghostty config from the current `LimpidSettings`
    /// and push it into the running app. Triggers
    /// `Notification.Name.limpidConfigDidChange` so SwiftUI views
    /// (and per-surface code) can react in the same tick.
    ///
    /// Surfaces opened *before* this call retain settings that
    /// libghostty marks as new-terminal only (font family, ligatures,
    /// scrollback). Settings libghostty applies live (font size,
    /// theme, opacity, cursor) reach every running surface
    /// immediately.
    static func reloadConfig(
        app: GhosttyApp,
        settings: LimpidSettings,
        resourcesDir: String?,
        includeUserConfig: Bool,
        appearance: Appearance,
        surfaces: [SurfaceView] = []
    ) {
        let path = writeConfigFile(
            settings: settings,
            resourcesDir: resourcesDir,
            appearance: appearance
        )
        guard let cfg = makeConfig(path: path, includeUserConfig: includeUserConfig) else {
            log.error("ghostty_config_new() returned nil during reload")
            return
        }
        // libghostty clones `cfg` internally (`apprt/embedded.zig`
        // calls `config.clone(alloc)`), so the caller still owns
        // this handle and MUST free it once the call returns. The
        // upstream macOS app does this through `Ghostty.Config`'s
        // `didSet { ghostty_config_free(old) }`; we free explicitly
        // here. A previous version of this code left the handle in
        // place on the false belief that ownership transferred, so
        // every reload (font size slider, theme switch, OS dark-mode
        // flip) leaked a multi-kB `Config` struct.
        defer { ghostty_config_free(cfg) }
        // App-level call delivers async messages to every surface's
        // renderer thread. Newly-spawned surfaces inherit the new
        // app-level config, so this still has to fire first.
        ghostty_app_update_config(app.handle, cfg)
        // Per-surface call routes through `Surface.updateConfig`
        // synchronously, so panes whose renderer thread is parked
        // (occluded, minimized, in-background tab) actually pick up
        // the new config instead of staying stuck on the old colors
        // until they are revealed. Mirrors the per-surface path
        // upstream Ghostty's macOS app adopted to resolve the same
        // class of "one pane stuck on the old theme" symptom.
        for view in surfaces {
            guard let surface = view.surface else { continue }
            ghostty_surface_update_config(surface, cfg)
        }
        NotificationCenter.default.post(
            name: .limpidConfigDidChange,
            object: nil
        )
        log.notice("ghostty config reloaded (\(surfaces.count, privacy: .public) live surfaces)")
    }

    /// Build a finalized libghostty config from the on-disk Limpid
    /// config file. The caller owns the returned handle — pass it to
    /// exactly one `ghostty_*_update_config` call.
    private static func makeConfig(path: String?, includeUserConfig: Bool) -> ghostty_config_t? {
        guard let cfg = ghostty_config_new() else { return nil }
        // Optional Layer 2: user's ~/.config/ghostty/config.
        // Forbidden keys still get neutralized because our forced
        // overrides append below them.
        if includeUserConfig {
            ghostty_config_load_default_files(cfg)
        }
        // Layer 3 + 4: Limpid settings + forced overrides.
        if let path {
            path.withCString { ghostty_config_load_file(cfg, $0) }
        }
        ghostty_config_finalize(cfg)
        return cfg
    }

    // MARK: - Mapping helpers

    /// Limpid's `CursorStyle` → libghostty's `cursor-style` value.
    private static func mapCursorStyle(_ style: CursorStyle) -> String {
        switch style {
        case .block: "block"
        case .bar: "bar"
        case .underline: "underline"
        }
    }

    /// Limpid's `BellAction` → libghostty's `bell-features` flags.
    /// Multiple flags space-separated.
    private static func mapBellFeatures(_ action: BellAction) -> String {
        switch action {
        case .none: "no-visual,no-audio,no-system,no-attention,no-title"
        case .visual: "visual,attention,no-audio,no-system"
        case .audio: "audio,attention,no-visual,no-system"
        case .both: "visual,audio,attention,no-system"
        }
    }
}

// MARK: - Notification name

extension Notification.Name {
    /// Posted by `GhosttyConfigBridge.reloadConfig` after libghostty
    /// has accepted the new config. Listeners (SwiftUI views, the
    /// SurfaceRegistry) re-evaluate any local cache that mirrored
    /// the old settings.
    static let limpidConfigDidChange = Notification.Name("dev.limpid.configDidChange")
}
