// GhosttyConfigBridge.swift
// Limpid — translates `LimpidSettings` into the `key = value\n` text
// libghostty parses, and applies it to the running app. The forced
// keys (transparent pane, no native window decoration, …) go *last*
// in the file so libghostty's last-write-wins merge silently
// overrides anything the user, `~/.config/ghostty/config`, or our
// own earlier lines wrote — cheaper than pre-parsing to filter.

import Foundation
import GhosttyKit
import OSLog

private let log = Logger.limpid("ghostty.config-bridge")

@MainActor
enum GhosttyConfigBridge {

    // MARK: - Serialization

    /// Build the full `key = value\n` string Limpid wants libghostty
    /// to evaluate. Order matters: user-facing settings first so the
    /// forced-overrides section at the bottom always wins.
    static func makeConfigString(
        settings: LimpidSettings,
        resourcesDir: String?
    ) -> String {
        var lines: [String] = [
            "# Generated by Limpid. Edits here are overwritten on every settings change.",
            "# Settings UI: ⌘, — file: \(SettingsStore.defaultSettingsFileURL.path)",
            ""
        ]

        // MARK: - User-facing settings → libghostty keys

        // Font
        if let family = settings.font.family, !family.isEmpty {
            // Strip any line terminator the value happens to carry —
            // libghostty's config is line-oriented, so an embedded
            // newline in a hand-edited `settings.json` would otherwise
            // inject extra config keys (`window-decoration = client`,
            // `command = …`) BEFORE the forced-overrides block. The
            // picker only offers `NSFontManager` families today, but
            // defensive sanitization at the splice site is cheap.
            let sanitized = family.replacingOccurrences(of: "\n", with: " ")
                .replacingOccurrences(of: "\r", with: " ")
            lines.append("font-family = \(sanitized)")
        }
        lines.append("font-size = \(settings.font.size)")
        if settings.font.ligatures {
            // Empty value clears libghostty's default "calt = 0" so
            // ligatures activate. Non-empty enables specific
            // OpenType features — left as default for now.
            lines.append("font-feature = ")
        } else {
            lines.append("font-feature = -calt")
        }
        if settings.font.lineHeight != 0 {
            lines.append("adjust-cell-height = \(Int(settings.font.lineHeight))")
        }

        // Terminal
        // The UI expresses this preference in lines. Ghostty's legacy
        // `scrollback-limit` spelling means bytes, while the explicit lines
        // key preserves the contract the picker presents. Remove the separate
        // byte ceiling so it cannot truncate history before the selected line
        // limit; allocation remains lazy and Ghostty compresses idle history.
        lines.append("scrollback-limit-lines = \(settings.terminal.scrollbackLines)")
        lines.append("scrollback-limit-bytes = unlimited")
        lines.append("cursor-style = \(mapCursorStyle(settings.terminal.cursorStyle))")
        lines.append("cursor-style-blink = \(settings.terminal.cursorBlink.isOn)")

        // Breathing room between the cell grid and the pane's edges.
        // The pane is flush to its column, because a full-width row —
        // a tmux status bar is the one that shows it — has to reach the
        // edge, and a SwiftUI padding around the surface would inset
        // that row along with everything else. Padding the grid from
        // inside the terminal separates the two: `extend` carries the
        // nearest cell's background into the padding, so a colored
        // full-width row still runs edge to edge while ordinary text
        // keeps its margin. libghostty's own default is 2, which reads
        // as no margin at all once the pane stopped being inset.
        lines.append("window-padding-x = 8")
        lines.append("window-padding-color = extend")

        // Theme: pick the bundled `Apple System Colors` pair so the
        // cell foreground + ANSI palette track macOS Terminal.app.
        // Use an absolute path because libghostty's named-theme lookup only
        // checks `~/.config/ghostty/themes/` and a hardcoded
        // `Ghostty.app/...` — neither sees our Limpid.app bundle.
        if let resourcesDir {
            let light = "\(resourcesDir)/themes/Apple System Colors Light"
            let dark = "\(resourcesDir)/themes/Apple System Colors"
            lines.append("theme = light:\(light),dark:\(dark)")
        }

        // MARK: - Forced overrides — must go LAST so libghostty's

        // last-write-wins merging guarantees they stick even if user
        // config or some earlier line set them otherwise.

        lines.append("")
        lines.append("# Limpid forced overrides — do not override these in user config.")
        lines.append("# Liquid Glass toolbar relies on these exact values.")
        // Terminal cells stay fully transparent — the wallpaper /
        // window opacity is the user-facing transparency knob, not
        // libghostty's per-cell tint. The trade-off is that Theme
        // only colors text + ANSI palette (not the cell bg), which
        // is the design we chose to keep Limpid's toolbar consistent
        // across themes.
        lines.append("background-opacity = 0")
        // libghostty exports the database beside its resources directory as
        // TERMINFO. Check the exact compiled alias before advertising it so a
        // partial development/package build falls back instead of leaving
        // every curses program unable to resolve $TERM.
        lines.append("term = \(resolvedTerm(resourcesDir: resourcesDir))")
        // Limpid handles its own close-confirm via SwiftUI .alert,
        // so disable libghostty's confirm dialog.
        lines.append("confirm-close-surface = false")
        // Review pastes repository content — a diff an agent wrote, or one
        // that arrived with a clone — into whatever the pane is running. The
        // confirmation an unbracketed multi-line paste goes through is what
        // keeps a shell from taking those lines as commands, so it is not a
        // setting a layered user config may switch off.
        lines.append("clipboard-paste-protection = true")
        // Tell shell integration to keep its hands off the cursor. Preserve
        // the bundled TERMINFO through local sudo, and keep SSH compatible
        // with hosts that do not have xterm-ghostty installed. We do not turn
        // on ssh-terminfo because silently installing files on a remote host
        // exceeds an embedded terminal's local configuration responsibility.
        // Default zsh / fish integration sends DECSCUSR (`ESC[<n> q`)
        // on every prompt, which clobbers Limpid's `cursor-style`
        // preference on the next keystroke. We own this setting
        // through Settings → Terminal → Cursor, so the prompt-time
        // override is always wrong here. (See Ghostty discussions
        // #3836 / #5144 / #8681 — the long-standing pitfall behind
        // "cursor-style doesn't change on existing shells".)
        lines.append("shell-integration-features = no-cursor,sudo,ssh-env")
        // Limpid never loads custom shaders, so disable the draw timer
        // that fires at 120 Hz (DRAW_INTERVAL = 8 ms) when the surface
        // is focused. Without this, every focused surface burns ~120
        // wakeups/s even at idle.
        lines.append("custom-shader-animation = false")

        // MARK: - Pattern A — single source of truth for keybinds

        //
        // Wipe libghostty's built-in macOS defaults so the menu bar
        // owns every shortcut; without `clear` a user remap (e.g.
        // "New Tab" → ⌘⇧T) would leave libghostty still firing its
        // own ⌘T behind the user's back. Forced bindings + the
        // user-configured action keybinds get re-emitted below.
        lines.append("keybind = clear")
        // Defense-in-depth against libghostty's `super+q=quit`
        // racing AppKit's terminate path (which fires
        // `applicationWillTerminate` and persists scrollback). ⌘Q is
        // already routed to the menu via
        // `SurfaceView.performKeyEquivalent`, but unbinding here
        // covers any future keystroke-routing change.
        lines.append("keybind = super+q=unbind")
        // Legacy XTerm key encoding emits identical bytes for ↩
        // and ⇧↩, so TUIs can't tell them apart. Mapping ⇧↩ to a
        // literal newline matches the recommended bare-ghostty
        // workaround (ghostty discussion #7780).
        lines.append(#"keybind = shift+enter=text:\n"#)

        lines.append(contentsOf: actionKeybindLines(settings: settings))

        return lines.joined(separator: "\n") + "\n"
    }

    /// One `keybind = …` line per `LimpidShortcutAction` with a
    /// configured trigger. Ghostty-dispatched actions
    /// (`ghosttyAction != nil`) emit the real action so libghostty
    /// fires it when the terminal has focus. Menu-owned actions
    /// (`ghosttyAction == nil`) emit `=ignore` — a disabled menu
    /// item lets the keystroke fall through to the focused
    /// terminal, and without `ignore` libghostty would type the
    /// literal character ("j", "R", …). An enabled menu item
    /// consumes the event before libghostty sees it, so `ignore`
    /// only fires on the disabled path.
    private static func actionKeybindLines(settings: LimpidSettings) -> [String] {
        var out: [String] = []
        for action in LimpidShortcutAction.allCases {
            guard let shortcut = settings.keyboard.shortcut(for: action) else { continue }
            let rhs = action.ghosttyAction ?? "ignore"
            out.append("keybind = \(shortcut.ghosttyTrigger)=\(rhs)")
        }
        return out
    }

    /// Write the config string to a stable temp file and return its
    /// path. Caller passes the path to `ghostty_config_load_file`.
    /// The same path is reused for live reloads — `update_config`
    /// looks at file mtime, so we overwrite atomically.
    static func writeConfigFile(
        settings: LimpidSettings,
        resourcesDir: String?,
        directory: URL? = nil,
        processID: Int32 = ProcessInfo.processInfo.processIdentifier
    ) -> String? {
        let body = makeConfigString(
            settings: settings,
            resourcesDir: resourcesDir
        )
        let dir = directory?.path ?? (NSTemporaryDirectory() as NSString).appendingPathComponent("dev.limpid")
        try? FileManager.default.createDirectory(atPath: dir, withIntermediateDirectories: true)
        // We isolate concurrent Dev and Release instances so one cannot replace
        // the file between another instance writing it and libghostty reading it.
        let name = "ghostty-config-\(processID).limpid"
        let path = (dir as NSString).appendingPathComponent(name)
        do {
            try body.write(toFile: path, atomically: true, encoding: .utf8)
            return path
        } catch {
            log.error("config file write failed: \(String(describing: error), privacy: .public)")
            return nil
        }
    }

    // MARK: - Live reload

    /// Finalize a config and copy its diagnostics. A path validates that file;
    /// `nil` validates Ghostty's default user config. Runtime callers invoke
    /// this before adding Limpid's generated layer so our errors are never
    /// attributed to the user's file.
    static func configDiagnostics(at path: String? = nil) -> [String]? {
        guard let cfg = ghostty_config_new() else {
            log.error("ghostty_config_new() returned nil during config validation")
            return nil
        }
        defer { ghostty_config_free(cfg) }
        if let path {
            path.withCString { ghostty_config_load_file(cfg, $0) }
        } else {
            ghostty_config_load_default_files(cfg)
        }
        ghostty_config_finalize(cfg)
        return GhosttyFFI.configDiagnostics(cfg)
    }

    /// Rebuild the libghostty config from the current `LimpidSettings`
    /// and push it into the running app. Triggers
    /// `Notification.Name.limpidConfigDidChange` so SwiftUI views
    /// (and per-surface code) can react in the same tick.
    ///
    /// Surfaces opened *before* this call retain settings that
    /// libghostty marks as new-terminal only (font family, ligatures,
    /// scrollback). Settings libghostty applies live (font size,
    /// theme, opacity, cursor) reach every running surface
    /// immediately.
    ///
    /// Returns diagnostics copied from the finalized user config, or `nil`
    /// when its validation handle could not be created.
    static func reloadConfig(
        app: GhosttyApp,
        settings: LimpidSettings,
        resourcesDir: String?,
        includeUserConfig: Bool,
        surfaces: [SurfaceView] = []
    ) -> [String]? {
        let diagnostics: [String]? = if includeUserConfig {
            configDiagnostics()
        } else {
            []
        }
        let path = writeConfigFile(
            settings: settings,
            resourcesDir: resourcesDir
        )
        guard let cfg = makeConfig(path: path, includeUserConfig: includeUserConfig) else {
            log.error("ghostty_config_new() returned nil during reload")
            return nil
        }
        // Ownership moves to GhosttyApp so a later conditional-state soft
        // reload uses this exact layered config rather than the startup copy.
        app.replaceConfig(with: cfg, surfaces: surfaces)
        NotificationCenter.default.post(
            name: .limpidConfigDidChange,
            object: nil
        )
        log.notice("ghostty config reloaded (\(surfaces.count, privacy: .public) live surfaces)")
        return diagnostics
    }

    /// Build a finalized libghostty config from the on-disk Limpid
    /// config file. The caller owns the returned handle — pass it to
    /// exactly one `ghostty_*_update_config` call.
    private static func makeConfig(path: String?, includeUserConfig: Bool) -> ghostty_config_t? {
        guard let cfg = ghostty_config_new() else { return nil }
        // Optional Layer 2: user's ~/.config/ghostty/config.
        // Forbidden keys still get neutralized because our forced
        // overrides append below them.
        if includeUserConfig {
            ghostty_config_load_default_files(cfg)
        }
        // Layer 3 + 4: Limpid settings + forced overrides.
        if let path {
            path.withCString { ghostty_config_load_file(cfg, $0) }
        }
        ghostty_config_finalize(cfg)
        return cfg
    }

    // MARK: - Mapping helpers

    /// Limpid's `CursorStyle` → libghostty's `cursor-style` value.
    private static func mapCursorStyle(_ style: CursorStyle) -> String {
        switch style {
        case .block: "block"
        case .bar: "bar"
        case .underline: "underline"
        }
    }

    static func resolvedTerm(resourcesDir: String?) -> String {
        guard let resourcesDir else { return "xterm-256color" }
        let database = URL(fileURLWithPath: resourcesDir)
            .deletingLastPathComponent()
            .appendingPathComponent("terminfo/78/xterm-ghostty")
        return FileManager.default.fileExists(atPath: database.path)
            ? "xterm-ghostty"
            : "xterm-256color"
    }

}

// MARK: - Notification name

extension Notification.Name {
    /// Posted by `GhosttyConfigBridge.reloadConfig` after libghostty
    /// has accepted the new config. Listeners (SwiftUI views, the
    /// SurfaceRegistry) re-evaluate any local cache that mirrored
    /// the old settings.
    static let limpidConfigDidChange = Notification.Name("dev.limpid.configDidChange")
}
