[package]
name = "limpid-rust-bridge"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
limpid-agent-core = { path = "../limpid-agent-core" }
limpid-agent-protocol = { path = "../limpid-agent-protocol" }
uuid.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
