#ifndef LIMPID_RUST_BRIDGE_H
#define LIMPID_RUST_BRIDGE_H

/* Generated by cbindgen from limpid-rust-bridge. Do not edit; run `make rust-header`. */

#include <stddef.h>
#include <stdint.h>

// Which hook entry point `limpid_hook_run_v1` runs.
#define LIMPID_HOOK_KIND_LIFECYCLE 0

// The worktree intercept the providers call on their shell tool.
#define LIMPID_HOOK_KIND_WORKTREE 1

// Status codes returned by the approval ABI functions.
//
// Every approval function reports its status as a plain `int32_t` so the C
// signature never depends on the enum's storage size; the enum exists so the
// generated header names each code for Swift.
typedef enum limpid_approval_result {
  // The discrete approval exchange completed and returned one JSON response.
  LIMPID_APPROVAL_OK = 0,
  // A required pointer was null.
  LIMPID_APPROVAL_NULL_POINTER = 1,
  // A UUID argument did not have its required 16-byte representation.
  LIMPID_APPROVAL_INVALID_UUID = 2,
  // The input exceeded the protocol's bounded request size.
  LIMPID_APPROVAL_INPUT_TOO_LARGE = 3,
  // The input was not UTF-8.
  LIMPID_APPROVAL_INVALID_UTF8 = 4,
  // The input was not one valid `WireRequest` JSON document.
  LIMPID_APPROVAL_INVALID_JSON = 5,
  // The response could not remain within the protocol's bounded size.
  LIMPID_APPROVAL_RESPONSE_TOO_LARGE = 6,
  // The service could not safely process the operation.
  LIMPID_APPROVAL_INTERNAL = 7,
  // Rust caught a panic at the FFI boundary.
  LIMPID_APPROVAL_PANIC = 8,
} limpid_approval_result;

// Status codes returned by `limpid_resolve_title_v1`, reported as `int32_t`
// for the same reason as `limpid_approval_result`.
typedef enum limpid_title_resolve_result {
  // The title was written to the caller-owned output buffer.
  LIMPID_TITLE_RESOLVE_OK = 0,
  // Every candidate was absent or blank.
  LIMPID_TITLE_RESOLVE_EMPTY = 1,
  // At least one candidate was not valid UTF-8.
  LIMPID_TITLE_RESOLVE_INVALID_UTF8 = 2,
  // At least one candidate exceeded the protocol limit.
  LIMPID_TITLE_RESOLVE_TOO_LONG = 3,
  // The output buffer was smaller than the selected title.
  LIMPID_TITLE_RESOLVE_BUFFER_TOO_SMALL = 4,
  // A non-empty input or output used a null pointer.
  LIMPID_TITLE_RESOLVE_NULL_POINTER = 5,
} limpid_title_resolve_result;

// Status codes returned by the provider translation ABI functions,
// reported as `int32_t` for the same reason as `limpid_approval_result`.
typedef enum limpid_provider_result {
  // The call succeeded and the output buffer holds the result.
  LIMPID_PROVIDER_OK = 0,
  // The payload is valid but is not a permission request; the output
  // buffer is empty.
  LIMPID_PROVIDER_NOT_APPROVAL = 1,
  // A required pointer was null.
  LIMPID_PROVIDER_NULL_POINTER = 2,
  // The provider id is not registered in this build.
  LIMPID_PROVIDER_UNKNOWN_PROVIDER = 3,
  // The input exceeded the hook payload limit.
  LIMPID_PROVIDER_INPUT_TOO_LARGE = 4,
  // The input was not UTF-8 or not the JSON shape the call expects.
  LIMPID_PROVIDER_INVALID_INPUT = 5,
  // The translation could not be serialized.
  LIMPID_PROVIDER_INTERNAL = 6,
  // Rust caught a panic at the FFI boundary.
  LIMPID_PROVIDER_PANIC = 7,
} limpid_provider_result;

// Status codes returned by the projection ABI functions, reported as
// `int32_t` for the same reason as `limpid_provider_result`.
typedef enum limpid_projection_result {
  // The call succeeded and the output buffer holds the result.
  LIMPID_PROJECTION_OK = 0,
  // A required pointer was null.
  LIMPID_PROJECTION_NULL_POINTER = 1,
  // The input exceeded the projection input limit.
  LIMPID_PROJECTION_INPUT_TOO_LARGE = 2,
  // The input was not UTF-8 or not the JSON shape the call expects.
  LIMPID_PROJECTION_INVALID_INPUT = 3,
  // The result could not be serialized.
  LIMPID_PROJECTION_INTERNAL = 4,
  // Rust caught a panic at the FFI boundary.
  LIMPID_PROJECTION_PANIC = 5,
} limpid_projection_result;

// Opaque service handle. Multiple sessions share its approval state.
typedef struct limpid_approval_service_v1 limpid_approval_service_v1;

// Opaque session handle. Its principal and hello state are host-bound.
typedef struct limpid_approval_session_v1 limpid_approval_session_v1;

// Bytes allocated by Rust for one response. Ownership transfers to the caller
// and must be released with `limpid_approval_bytes_free_v1`.
typedef struct limpid_approval_bytes_v1 {
  uint8_t *data;
  size_t len;
} limpid_approval_bytes_v1;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns the bridge-wide compatibility version. Adding a new symbol does not
// increment it; only an incompatible change to an existing contract does.
uint32_t limpid_rust_abi_version(void);

// Creates an approval service that can be shared by independently
// authenticated XPC connections.
//
// A service shares state among independent host-authenticated sessions. The
// caller must free every session before freeing its service. Calls on
// separate sessions may run concurrently; each session serializes its own use.
struct limpid_approval_service_v1 *limpid_approval_service_create_v1(size_t maximum_records);

// Releases a service handle after all sessions created from it have been
// released. Passing null is a no-op.
//
// # Safety
//
// `service` must be null or a live pointer returned by the matching create
// function and not previously freed.
void limpid_approval_service_free_v1(struct limpid_approval_service_v1 *service);

// Creates a requester session whose run ID is bound by the authenticated
// host, never taken from JSON. `run_id` is exactly 16 raw UUID bytes.
//
// # Safety
//
// `service` must be a live service handle. `run_id` must be readable for
// `run_id_len` bytes when non-null.
struct limpid_approval_session_v1 *limpid_approval_session_create_requester_v1(const struct limpid_approval_service_v1 *service,
                                                                               const uint8_t *run_id,
                                                                               size_t run_id_len);

// Creates a controller session for a host-authenticated controller principal.
//
// # Safety
//
// `service` must be a live service handle.
struct limpid_approval_session_v1 *limpid_approval_session_create_controller_v1(const struct limpid_approval_service_v1 *service);

// Releases a session handle. Passing null is a no-op.
//
// # Safety
//
// `session` must be null or a live pointer returned by a matching session
// constructor and not previously freed.
void limpid_approval_session_free_v1(struct limpid_approval_session_v1 *session);

// Exchanges exactly one complete `WireRequest` JSON document for exactly one
// `WireResponse` JSON document. It deliberately does not add stream framing:
// one XPC `Data` request maps to one request document and one response `Data`
// maps to one response document. On success, ownership of `output->data`
// transfers to the caller, which must release it with
// `limpid_approval_bytes_free_v1`.
//
// # Safety
//
// `session` and `output` must be live writable pointers. `input` may be null
// only when `input_len` is zero; otherwise it must be readable for its length.
int32_t limpid_approval_session_exchange_v1(struct limpid_approval_session_v1 *session,
                                            const uint8_t *input,
                                            size_t input_len,
                                            struct limpid_approval_bytes_v1 *output);

// Releases bytes this library handed out through an `out`/`out_len` pair:
// `limpid_approval_session_exchange_v1`, the `limpid_provider_*_v1`
// translations, and `limpid_hook_run_v1`. Passing null with a zero length
// is a no-op.
//
// # Safety
//
// The pair must be null/zero or exactly the pair returned by one successful
// call and not previously freed.
void limpid_approval_bytes_free_v1(uint8_t *data, size_t len);

// Resolves an automatic title into a caller-owned UTF-8 buffer.
//
// Each optional input uses a pointer-length pair. A zero length represents an
// absent candidate and permits a null pointer. The output is not NUL
// terminated; `output_length` receives the number of bytes written or the
// required capacity when the buffer is too small.
//
// # Safety
//
// Every non-null pointer must remain valid for its declared length for the
// duration of this call. Input regions must be readable, and the output region
// and `output_length` must be writable. The regions must not overlap.
int32_t limpid_resolve_title_v1(const uint8_t *provider_session_ptr,
                                size_t provider_session_len,
                                const uint8_t *provider_generated_ptr,
                                size_t provider_generated_len,
                                const uint8_t *first_prompt_ptr,
                                size_t first_prompt_len,
                                uint8_t *output_ptr,
                                size_t output_capacity,
                                size_t *output_length);

// Reports the providers this build has, as `{ "<id>": <descriptor>, ... }`.
//
// # Safety
//
// The output pointers must be writable. On `LIMPID_PROJECTION_OK` the caller
// owns the body and frees it with `limpid_approval_bytes_free_v1`.
int32_t limpid_projection_providers_v1(uint8_t **out, size_t *out_len);

// Reports what each installed provider needs the platform to set up.
//
// The body is `{ "<provider id>": <install recipe>, ... }`.
//
// # Safety
//
// The output pointers must be writable. On `LIMPID_PROJECTION_OK` the caller
// owns the body and frees it with `limpid_approval_bytes_free_v1`.
int32_t limpid_projection_install_recipes_v1(uint8_t **out, size_t *out_len);

// Reduces the records the host found into what to show and what to change.
//
// `state` is the body a previous call returned, or empty on the first call.
// `input` is the `ProjectionInput` JSON, `now` the `Instants` JSON.
//
// # Safety
//
// Every non-null pointer must remain valid for its declared length for the
// duration of this call. The output pointers must be writable, and on
// `LIMPID_PROJECTION_OK` the caller owns the body and frees it with
// `limpid_approval_bytes_free_v1`.
int32_t limpid_projection_project_v1(const uint8_t *state,
                                     size_t state_len,
                                     const uint8_t *input,
                                     size_t input_len,
                                     const uint8_t *now,
                                     size_t now_len,
                                     uint8_t **out,
                                     size_t *out_len);

// Decides what to restore or retire before the interface exists.
//
// # Safety
//
// As `limpid_projection_project_v1`.
int32_t limpid_projection_on_launch_v1(const uint8_t *input,
                                       size_t input_len,
                                       const uint8_t *now,
                                       size_t now_len,
                                       uint8_t **out,
                                       size_t *out_len);

// Records what Limpid is about to kill and what would bring it back.
//
// # Safety
//
// As `limpid_projection_project_v1`.
int32_t limpid_projection_on_terminate_v1(const uint8_t *input,
                                          size_t input_len,
                                          const uint8_t *now,
                                          size_t now_len,
                                          uint8_t **out,
                                          size_t *out_len);

// Runs one lifecycle or worktree hook call and reports the outcome as JSON:
// `{"outcome":"applied","exit_code":0}` or, after a worktree intercept,
// `{"outcome":"intercepted","exit_code":2,"message":"..."}`. Every other
// outcome (`not_in_limpid`, `rejected`, `unknown_provider`) carries exit
// code zero so the agent is never blocked. `env_json` is a JSON object of
// the process environment; the runtime reads the shim's variables from it
// rather than from the process so the host controls what the hook sees.
// This call opens no approval service connection. On success, ownership
// of `*out` transfers to the caller, which must release it with
// `limpid_approval_bytes_free_v1`.
//
// # Safety
//
// Same contract as `limpid_provider_approval_request_v1`, with `env_json`
// readable for `env_len` bytes.
int32_t limpid_hook_run_v1(const uint8_t *provider,
                           size_t provider_len,
                           uint32_t kind,
                           const uint8_t *input,
                           size_t input_len,
                           const uint8_t *env_json,
                           size_t env_len,
                           uint8_t **out,
                           size_t *out_len);

// Translates a provider's `PermissionRequest` payload into the neutral
// approval request as JSON.
//
// Returns `LIMPID_PROVIDER_OK` with a JSON body, `LIMPID_PROVIDER_NOT_APPROVAL`
// with an empty body when the payload is not a permission request, or an
// error code with an empty body. On success, ownership of `*out` transfers to
// the caller, which must release it with `limpid_approval_bytes_free_v1`.
//
// # Safety
//
// `out` and `out_len` must be writable. `provider` must be readable for
// `provider_len` bytes and `input` for `input_len` bytes; either may be null
// only when its length is zero.
int32_t limpid_provider_approval_request_v1(const uint8_t *provider,
                                            size_t provider_len,
                                            const uint8_t *input,
                                            size_t input_len,
                                            uint8_t **out,
                                            size_t *out_len);

// Renders a neutral decision as the provider's hook output.
//
// `decision_json` is an `ApprovalDecision` document such as
// `{"decision":"allow_once"}` or `{"decision":"deny","message":"..."}`.
// Returns `LIMPID_PROVIDER_OK` with the bytes to write to the hook's standard
// output; an empty body means the provider's native flow decides. On
// success, ownership of `*out` transfers to the caller, which must release
// it with `limpid_approval_bytes_free_v1`.
//
// # Safety
//
// Same contract as `limpid_provider_approval_request_v1`.
int32_t limpid_provider_approval_output_v1(const uint8_t *provider,
                                           size_t provider_len,
                                           const uint8_t *decision_json,
                                           size_t decision_len,
                                           uint8_t **out,
                                           size_t *out_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LIMPID_RUST_BRIDGE_H */
